### PR TITLE
Improve sections of documentation 

### PR DESCRIPTION
**Pull request by purbon**
This PR improve sections of documentation about:

* The core concepts and why and where the plugin is worth using it. (bring in also an example)
* Extend the demo part of the documentation with an easy to follow example where people can related about the algorithm functionality.

@chatox @MilkaLichtblau thoughts about it?  you can see latest changes http://fairsearch-elasticsearch.readthedocs.io/en/feature-docs/

### CODE REVIEW

**Comment by chatox** [comment]
Hi, I like this! I just wouldn't mention XING explicitly (i.e., "a large job search engine").

I also would like to do some small edits/corrections over what you generated. From the command line, what should I do? I'm sorry, I only know the basics, e.g., I've never done a pull request, just git clone/push/pull, so I would need a couple of instructions to get me started. Thank you.

**Comment by purbon** [comment]
great @chatox, to do that you can use the same github ui.
Please follow this link https://github.com/fair-search/fairsearch-elasticsearch-plugin/tree/feature/docs/docs and edit any of the .rst files in there. Each of this files represent one of the biggest sections you can see in the documentation.

To edit the file you have to click the edit this file button, second one top right of the screen.

After you are done with the edit, you can just do a new commit and all will show in this pr.

After each one of your commits, and waiting for the sync to happen, you will see your changes in http://fairsearch-elasticsearch.readthedocs.io/en/feature-docs/

Happy to help,

**Comment by purbon** [comment]
another option you have is to do a comment in this pr, then I will do the changes myself. For this you just go to the files changes section of this PR and do a comment wherever you are for it.

**Comment by chatox** [comment]
@purbon I've edited the documentation. Please take a look again, if you see something wrong (e.g., broken link or formatting) please let me know. Otherwise accept and merge with the main branch. Thank you.

**Comment by purbon** [comment]
@chatox good work man! that a lot of rewrite. I will take a look and merge as soon as posible.

**Comment by purbon** [comment]
@chatox  did the changes and the reorg as we spoke over video, I will merge this PR, if you find another issues, I will address them in another PR.

**Pull request merged**
